rpi-eventhub/README.md

updated readme

---

rpi-eventhub/react_docs/documentation.txt

Here, I created an ongoing documentation as I am learning React, and for those that are interested or need help in React.

created documentation for react

---

rpi-eventhub/src/pages/AboutUs/AboutUs.js
rpi-eventhub/src/pages/Events/Events.js

Fixed the bug where the navbar would left-align on the events and about us page. Also fixed some other typos in the code such as the functions in Events.js being named "AboutUs()".

Fixed Navbar Centering

---

.gitignore
rpi-eventhub/.gitignore

Debug dependency

---

rpi-eventhub/frontend/src/components/Navbar/Navbar.css

Just making nav bar looking better

---

rpi-eventhub/backend/index.js
rpi-eventhub/backend/models/User.js

added like endpoint which only allow verified and logged in users to like events

added like endpoint

---

rpi-eventhub/frontend/src/components/Carousel/Carousel.css
rpi-eventhub/frontend/src/components/Carousel/Carousel.js

Got rid of top previews of other images, added automatic transition feature to next image, fixed css accordingly

updated carousel component

---

rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.js
rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.modular.css
rpi-eventhub/frontend/src/pages/Events/Events.css
rpi-eventhub/frontend/src/pages/Events/Events.js
rpi-eventhub/frontend/src/pages/Home/Home.js
rpi-eventhub/frontend/src/pages/Home/Home.module.css

I added simple animations for all the elements of the home and events page (about us page already had them) that happen when traveling to that page. The text fades in and components or images fade in and scale up slightly. I also added code to scroll to the top of every page when clicking on it.

CSS Page Animations

---

rpi-eventhub/frontend/src/components/EventPosterOnly/EventPoster.css
rpi-eventhub/frontend/src/components/EventPosterOnly/EventPoster.js
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.js

CSS logic + data structure change

Fixed poster dynamic scaling

---

rpi-eventhub/frontend/src/components/SignupModal/SignupModal.js
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.js

Added check to make sure users can only create an account if they are using an rpi email. Also added a sort feature to the displaying of events in the event page, which displays the latest dates first and the earliest dates last. This way users can see the events in the future before ones in the past.

Login RPI email & Sort descending order of date of event

---

README.md
rpi-eventhub/frontend/src/components/Carousel/Carousel.js

Implemented pauseAutoplay. Added onMouseEnter and onMouseLeave so now the carousel stops autoplay when user hover on the image.

Pause carousel autoplay

---

rpi-eventhub/frontend/package-lock.json
rpi-eventhub/frontend/package.json
rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.js
rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.module.css

Fetched contributor username and profile picture with GitHub API and updated styling.

Using GitHub api to fetch developers

---

rpi-eventhub/frontend/src/components/App/App.js
rpi-eventhub/frontend/src/components/SearchBar/SearchBar.js
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.js
rpi-eventhub/frontend/src/pages/SearchResults/SearchResults.js
rpi-eventhub/frontend/src/pages/SearchResults/SearchResults.module.css

Added search function that searches through events list and outputs any results whose title has at least one word in common with the search query. Redirects to a new page to output the search results.

SearchBar Functionality

---

rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.css
rpi-eventhub/frontend/src/components/LoginButton/LoginButton.module.css
rpi-eventhub/frontend/src/components/Navbar/Navbar.js
rpi-eventhub/frontend/src/components/Navbar/Navbar.module.css

Reverts MeiH10/RPI-EventHub#140

Revert "Fixed Navbar tab orderings"

---

rpi-eventhub/frontend/src/components/App/App.js
rpi-eventhub/frontend/src/components/Navbar/Navbar.js
rpi-eventhub/frontend/src/pages/Calendar/Calendar.js
rpi-eventhub/frontend/src/pages/Calendar/Calendar.module.css

Began working on calendar page, still needs some work to match the one on Figma

Started calendar page

---

rpi-eventhub/frontend/src/components/Navbar/Navbar.js
rpi-eventhub/frontend/src/components/Navbar/Navbar.module.css

The navbar now resembles the Figma one, and the hamburger menu and logo are in correct locations.. navMenu2 and navMenu3 created to contain and separate them on the navbar

Navbar appearance

---

package-lock.json
package.json
rpi-eventhub/backend/index.js
rpi-eventhub/backend/models/Event.js
rpi-eventhub/frontend/src/components/App/App.js
rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.js
rpi-eventhub/frontend/src/components/EventPosterOnly/EventPoster.js
rpi-eventhub/frontend/src/components/rsvp-button/RsvpButton.js
rpi-eventhub/frontend/src/components/rsvp-button/RsvpButton.module.css
rpi-eventhub/frontend/src/pages/EventDetails/EventDetails.js
rpi-eventhub/frontend/src/pages/EventDetails/EventDetails.module.css

The single event page provides users with information about a specific event. Added the "EventDetails" page to display info about a single event, and connected it with the backend. It also includes an RSVP button for users to register at.

Single event page

---

rpi-eventhub/frontend/src/pages/Calendar/Calendar.js
rpi-eventhub/frontend/src/pages/Calendar/Calendar.module.css

Modified the calendar design. Not planning on using react libraries for calendar because the libraries will display an actual calendar and not the one we have designed on the mockup page.

modified calendar design

---

rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.js

Finished implementing success and error messages for the create event form. When a user does not enter all required fields, an error message displays prompting the user to enter all required fields. If the user enters all required fields and is able to create the event, a success message is displayed indicating that the user has successfully created the event.

Success message and error message 

---

rpi-eventhub/frontend/src/components/SearchBar/SearchBar.js

Just added a couple of lines that also display matching events based on one or more tag matches

Added search by tags

---

rpi-eventhub/frontend/src/components/App/App.js
rpi-eventhub/frontend/src/components/Navbar/Navbar.module.css
rpi-eventhub/frontend/src/components/SignupModal/SignupModal.js
rpi-eventhub/frontend/src/index.css
rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.module.css
rpi-eventhub/frontend/src/pages/TermsOfService/TermsOfService.js
rpi-eventhub/frontend/src/pages/TermsOfService/TermsOfService.module.css

Added Terms of Service link and checkbox to the sign up modal, making it required and also changed the font to a Georgia for the rest of the site.

Terms of service

---

rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.js
rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.module.css
rpi-eventhub/frontend/src/context/ThemeContext.js
rpi-eventhub/frontend/src/hooks/useColorScheme.js

make it so that user can't keep spamming the same tag(maybe make it so that click once selects the tag, click twice unselect the tag. Max 10 tags

improved suggest tag button

---

rpi-eventhub/frontend/src/components/FilterBar/FilterBar.jsx
rpi-eventhub/frontend/src/components/FilterBar/FilterBar.module.css
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.jsx
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.module.css

- Redesign the filter and button in mobile
- Redesign the checkbox
- Fixed the filter on the screen

[Feature] Brand new filter bar

---

RPI EventHub Manual.md

SIte manual

---

rpi-eventhub/frontend/src/components/Navbar/Navbar.module.css
rpi-eventhub/package-lock.json

Removed second bar on navbar links

Fixed Navbar Hover

---

rpi-eventhub/frontend/src/components/FilterBar/FilterBar.jsx
rpi-eventhub/frontend/src/components/FilterBar/FilterBar.module.css
rpi-eventhub/frontend/src/pages/Events/AllEventList/EventsList.jsx
rpi-eventhub/frontend/src/pages/Events/AllEventList/EventsList.module.css
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.jsx
rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.module.css

Events list view

---

rpi-eventhub/frontend/src/pages/AboutUs/AboutUs.jsx
rpi-eventhub/frontend/src/pages/Calendar/Calendar.jsx

About us edit

---

rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.jsx
rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.module.css

- Make Choose File Button Show correctly in file upload section

[BugFix] Make Button Show correctly

---

rpi-eventhub/backend/index.js
rpi-eventhub/backend/routes/eventRoutes.js
rpi-eventhub/frontend/src/components/CreateEventModal/CreateEventModal.jsx

about changes in routes file: we had 2 createEvent functions, the one in the routes was not running.

added the duplicate check before posting the event

---

rpi-eventhub/frontend/index.html
rpi-eventhub/frontend/package-lock.json
rpi-eventhub/frontend/package.json

Added Google Analytics tag to index.html

Google Analytics

---

rpi-eventhub/frontend/src/pages/Calendar/Calendar.jsx
rpi-eventhub/frontend/src/pages/Calendar/Calendar.module.css

the improvement of no image performance.

---

rpi-eventhub/backend/sqldb.js

added image compression and uploading to imgbb for images sourced from corbin's database.

Image resizing from corbin's database

---

rpi-eventhub/frontend/src/components/Navbar/Navbar.jsx
rpi-eventhub/frontend/src/components/Navbar/Navbar.module.css

update of navbar color

---

rpi-eventhub/frontend/src/pages/Calendar/Calendar.jsx
rpi-eventhub/frontend/src/pages/Calendar/Calendar.module.css

```html
<h3 className={`text-[10px] md:text-xs font-bold truncate ${isDark ? 'text-white' : 'text-black'}`}>
{event.title}
</h3>
```
**html2Canvas** cannot handle truncate style by tailwind CSS.
remove the truncate style while capturing.

[BugFix] The texts crop bug fixed

---

rpi-eventhub/backend/services/userService.js
rpi-eventhub/frontend/src/components/AdminSearch/AdminSearch.jsx
rpi-eventhub/frontend/src/pages/AdminPage/AdminPage.jsx
rpi-eventhub/frontend/src/pages/AdminPage/AdminPageNotes.md

The PR adds the Admin Page functionality to pull real user stats from the server.
Note that the endpoint used is also exposed to a regular user.
Note that the ability to demote/promote users is not added currently.
The PR also has documentation for what is done, as well as what needs to be done.

Fetching real user stats
